appmongo:
  image: mongo:3
  command: mongod --noauth --storageEngine wiredTiger --wiredTigerDirectoryForIndexes --directoryperdb

#backupmongo:
#  image: mongo:3
#  command: mongod --noauth --storageEngine wiredTiger --wiredTigerDirectoryForIndexes --httpinterface --directoryperdb

opsmanager:
  build: .
  links:
    - appmongo:appmongo
    #- backupmongo:backupmongo
  ports:
    - "172.17.0.1:18080:8080"
    - "172.17.0.1:18081:8081"
  volumes:
    #- ./mms/conf:/opt/mongodb/mms/conf
    - ./mms/logs:/opt/mongodb/mms/logs
    